spring:
  application:
    name: bsmart-score-tracker-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8889}
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 1000
